export default Images = {
  back: require('../assets/images/SplashScreen.jpg'),
  logo: require('../assets/images/logo2.png'),
  logo1: require('../assets/images/logo2.png'),
  logo2: require('../assets/images/logo.png'),

  user: require('../assets/images/user.png'),
  lock: require('../assets/images/lock.png'),
  loginImage: require('../assets/images/loginImage.png'),
  blood: require('../assets/images/blood.png'),
  facebook: require('../assets/images/facebook.png'),
  google: require('../assets/images/google.png'),
  phone: require('../assets/images/phone.png'),
  apple: require('../assets/images/apple.png'),
  leftarrow: require('../assets/images/left-arrow.png'),
  slide1: require('../assets/images/slide1.png'),
  slide2: require('../assets/images/slide2.png'),
  slide3: require('../assets/images/slide3.png'),
  slide4: require('../assets/images/slide4.png'),

  b1: require('../assets/images/b1.jpeg'),
  b2: require('../assets/images/b2.jpeg'),
  b3: require('../assets/images/b3.jpeg'),
  b4: require('../assets/images/b4.jpeg'),
  b5: require('../assets/images/b5.jpeg'),
  b6: require('../assets/images/b6.jpeg'),
  left: require('../assets/images/left.png'),
  right: require('../assets/images/right.png'),
  drop: require('../assets/images/drop.png'),

  assistant: require('../assets/images/assistant.png'),
  donates: require('../assets/images/donates.png'),
  donor: require('../assets/images/donor.png'),
  orderBlood: require('../assets/images/orderBlood.png'),
  compaign: require('../assets/images/compaign.png'),
  report: require('../assets/images/report.png'),
  man: require('../assets/images/man.png'),
  women: require('../assets/images/woman.png'),
  man1: require('../assets/images/man1.png'),
  women1: require('../assets/images/woman1.png'),
  profile: require('../assets/images/profile.png'),
  filter: require('../assets/images/filter.png'),
  pin: require('../assets/images/map-pin.png'),
  pana: require('../assets/images/pana.png'),
  next: require('../assets/images/next.png'),
  splash: require('../assets/images/splash.png'),
  success: require('../assets/images/success.png'),
  reportImage: require('../assets/images/reportImage.png'),
  don: require('../assets/images/don.png'),
  droplight: require('../assets/images/droplight.png'),
  callnow: require('../assets/images/callnow.png'),

  share: require('../assets/images/share.png'),

  logout: require('../assets/images/logout.png'),
  availability: require('../assets/images/availability.png'),
  invite: require('../assets/images/invite.png'),
  info: require('../assets/images/info.png'),
  camp1: require('../assets/images/camp1.jpeg'),
  camp2: require('../assets/images/camp2.jpeg'),
  camp3: require('../assets/images/camp3.jpeg'),
  camp4: require('../assets/images/camp4.jpeg'),
  camp5: require('../assets/images/camp5.jpeg'),
  pending1: require('../assets/images/pending1.png'),
  pending2: require('../assets/images/pending2.png'),
  appoinment: require('../assets/images/deadline.png'),
};
